pooler_config:
    embed_dim: 1536
    num_heads: 24
    mlp_ratio: 4.0
    depth: 2
global_embeddings_vision: False
global_embeddings_text: False
no_caption_loss: True
text_dim_local: 768
text_dim_global: 256
vision_dim: 1408

learning_rate: 0.0003
weight_decay: 0.01

batch_size: 256
max_epochs: 100