pooler_config:
    embed_dim: 512
    num_heads: 8
    mlp_ratio: 4.0
    depth: 2
global_embeddings_vision: True
global_embeddings_text: True
text_dim: 512
vision_dim: 512

learning_rate: 0.0003
weight_decay: 0.01

batch_size: 8
max_epochs: 30
